"""
Monte Carlo Simulation for SMC Layer Signals
============================================
This script runs Monte Carlo simulations on the signals generated by the SMC layers
and produces a comprehensive performance report.

The simulation:
1. Loads historical signals from upgraded_signals.csv
2. Simulates trade outcomes using historical price data
3. Runs Monte Carlo iterations to project performance
4. Generates statistical analysis and visualizations
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Configuration
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'data')

# ============================================================================
# CONFIGURATION
# ============================================================================
INITIAL_BALANCE = 100.0  # Starting account balance
RISK_PER_TRADE = 0.02  # 2% risk per trade
REWARD_TO_RISK = 2.0  # 2:1 reward to risk ratio
MONTE_CARLO_ITERATIONS = 10000  # Number of Monte Carlo iterations
TRADING_DAYS_PER_YEAR = 252

# ============================================================================
# SIGNAL ANALYSIS
# ============================================================================
def load_signals():
    """Load historical signals from CSV."""
    signal_file = os.path.join(DATA_DIR, 'upgraded_signals.csv')
    
    if not os.path.exists(signal_file):
        print(f"ERROR: Signal file not found: {signal_file}")
        return None
    
    df = pd.read_csv(signal_file)
    df['Time'] = pd.to_datetime(df['Time'])
    df = df.sort_values('Time')
    
    print(f"\n{'='*60}")
    print("SIGNAL DATA SUMMARY")
    print(f"{'='*60}")
    print(f"Total signals: {len(df)}")
    print(f"Date range: {df['Time'].min()} to {df['Time'].max()}")
    print(f"Duration: {(df['Time'].max() - df['Time'].min()).days} days")
    print(f"\nSignal distribution:")
    print(f"  LONG signals: {len(df[df['Action'] == 'LONG'])}")
    print(f"  SHORT signals: {len(df[df['Action'] == 'SHORT'])}")
    
    # Analyze by hour
    df['Hour'] = df['Time'].dt.hour
    print(f"\nSignals by hour of day:")
    hour_dist = df.groupby('Hour').size()
    for hour, count in hour_dist.items():
        print(f"  {hour:02d}:00 - {count} signals")
    
    return df

def analyze_session_distribution(df):
    """Analyze signal distribution across trading sessions."""
    df = df.copy()
    
    # Convert to UTC for session analysis
    # Assuming data is in UTC
    df['Hour_UTC'] = df['Time'].dt.hour
    
    # Define sessions (UTC times)
    def get_session(hour):
        if 7 <= hour < 10:
            return 'London Open'
        elif 10 <= hour < 16:
            return 'London Session'
        elif 12 <= hour < 15:
            return 'NY Open'
        elif 15 <= hour < 21:
            return 'NY Session'
        else:
            return 'Off Hours'
    
    df['Session'] = df['Hour_UTC'].apply(get_session)
    
    print(f"\n{'='*60}")
    print("SESSION DISTRIBUTION ANALYSIS")
    print(f"{'='*60}")
    session_dist = df.groupby('Session').size()
    for session, count in session_dist.items():
        pct = count / len(df) * 100
        print(f"  {session}: {count} signals ({pct:.1f}%)")
    
    return df

def estimate_win_rate(df):
    """Estimate historical win rate based on signals."""
    # For XAUUSD with 2:1 R/R, we need ~33% win rate to break even
    # Historical data suggests 40-50% win rate is typical for SMC strategies
    
    # Calculate based on action and price movement patterns
    # We'll use a realistic estimate based on the strategy
    
    # Group consecutive signals and estimate outcomes
    df = df.sort_values('Time').reset_index(drop=True)
    
    # Calculate price changes after each signal
    wins = 0
    losses = 0
    break_even = 0
    
    for i in range(len(df) - 1):
        signal_price = df.iloc[i]['Price']
        next_price = df.iloc[i + 1]['Price']
        action = df.iloc[i]['Action']
        
        price_change = ((next_price - signal_price) / signal_price) * 100
        
        if action == 'LONG':
            if price_change > 0:
                wins += 1
            elif price_change < 0:
                losses += 1
            else:
                break_even += 1
        else:  # SHORT
            if price_change < 0:
                wins += 1
            elif price_change > 0:
                losses += 1
            else:
                break_even += 1
    
    total = wins + losses + break_even
    if total > 0:
        win_rate = wins / total
    else:
        win_rate = 0.45  # Default estimate
    
    print(f"\n{'='*60}")
    print("HISTORICAL WIN RATE ESTIMATION")
    print(f"{'='*60}")
    print(f"  Estimated win rate: {win_rate:.1%}")
    print(f"  Total signal pairs analyzed: {total}")
    print(f"  Wins: {wins}, Losses: {losses}, Break-even: {break_even}")
    
    return win_rate

# ============================================================================
# MONTE CARLO SIMULATION
# ============================================================================
def run_monte_carlo_simulation(signals_df, initial_balance, risk_per_trade, 
                                reward_to_risk, iterations):
    """Run Monte Carlo simulation on trading signals."""
    
    num_signals = len(signals_df)
    win_rate = estimate_win_rate(signals_df)
    
    print(f"\n{'='*60}")
    print("MONTE CARLO SIMULATION PARAMETERS")
    print(f"{'='*60}")
    print(f"  Initial balance: ${initial_balance:.2f}")
    print(f"  Risk per trade: {risk_per_trade:.1%}")
    print(f"  Reward-to-Risk: {reward_to_risk:.1f}:1")
    print(f"  Number of trades: {num_signals}")
    print(f"  Win rate: {win_rate:.1%}")
    print(f"  Iterations: {iterations}")
    
    # Calculate expected value
    expected_value = (win_rate * reward_to_risk) - ((1 - win_rate) * 1)
    print(f"  Expected value per trade: {expected_value:.3f}")
    
    # Run simulations
    final_balances = []
    max_drawdowns = []
    trade_sequences = []
    
    for i in range(iterations):
        balance = initial_balance
        peak_balance = initial_balance
        max_dd = 0
        
        balances = [balance]
        
        for j in range(num_signals):
            # Simulate trade outcome
            if np.random.random() < win_rate:
                # Win: gain risk * reward_to_risk
                balance += balance * risk_per_trade * reward_to_risk
            else:
                # Loss: lose risk amount
                balance -= balance * risk_per_trade
            
            # Track drawdown
            if balance > peak_balance:
                peak_balance = balance
            
            dd = (peak_balance - balance) / peak_balance
            if dd > max_dd:
                max_dd = dd
            
            balances.append(balance)
        
        final_balances.append(balance)
        max_drawdowns.append(max_dd)
        trade_sequences.append(balances)
    
    return {
        'final_balances': final_balances,
        'max_drawdowns': max_drawdowns,
        'trade_sequences': trade_sequences,
        'num_signals': num_signals,
        'win_rate': win_rate,
        'expected_value': expected_value
    }

def analyze_results(results, initial_balance, iterations):
    """Analyze and report Monte Carlo simulation results."""
    
    final_balances = np.array(results['final_balances'])
    max_drawdowns = np.array(results['max_drawdowns'])
    
    print(f"\n{'='*60}")
    print("MONTE CARLO SIMULATION RESULTS")
    print(f"{'='*60}")
    
    # Final balance statistics
    print(f"\n--- FINAL BALANCE STATISTICS ---")
    print(f"  Mean final balance: ${np.mean(final_balances):.2f}")
    print(f"  Median final balance: ${np.median(final_balances):.2f}")
    print(f"  Std deviation: ${np.std(final_balances):.2f}")
    print(f"  Min: ${np.min(final_balances):.2f}")
    print(f"  Max: ${np.max(final_balances):.2f}")
    
    # Percentiles
    print(f"\n--- PERCENTILE ANALYSIS ---")
    for pct in [5, 10, 25, 50, 75, 90, 95]:
        balance = np.percentile(final_balances, pct)
        roi = ((balance - initial_balance) / initial_balance) * 100
        print(f"  {pct}th percentile: ${balance:.2f} ({roi:+.1f}% ROI)")
    
    # Drawdown statistics
    print(f"\n--- MAXIMUM DRAWDOWN STATISTICS ---")
    print(f"  Mean max DD: {np.mean(max_drawdowns)*100:.1f}%")
    print(f"  Median max DD: {np.median(max_drawdowns)*100:.1f}%")
    print(f"  Worst case: {np.max(max_drawdowns)*100:.1f}%")
    
    # Probability analysis
    print(f"\n--- PROBABILITY ANALYSIS ---")
    profitable_count = np.sum(final_balances > initial_balance)
    double_count = np.sum(final_balances >= initial_balance * 2)
    wiped_out_count = np.sum(final_balances < initial_balance * 0.5)
    
    print(f"  Probability of profit: {profitable_count/iterations*100:.1f}%")
    print(f"  Probability of doubling: {double_count/iterations*100:.1f}%")
    print(f"  Probability of 50% loss: {wiped_out_count/iterations*100:.1f}%")
    
    # Return statistics
    returns = (final_balances - initial_balance) / initial_balance * 100
    
    print(f"\n--- RETURN STATISTICS ---")
    print(f"  Mean return: {np.mean(returns):.1f}%")
    print(f"  Median return: {np.median(returns):.1f}%")
    print(f"  Best case: {np.max(returns):.1f}%")
    print(f"  Worst case: {np.min(returns):.1f}%")
    
    return {
        'mean_balance': np.mean(final_balances),
        'median_balance': np.median(final_balances),
        'std_balance': np.std(final_balances),
        'prob_profit': profitable_count / iterations,
        'prob_doubling': double_count / iterations,
        'prob_50_loss': wiped_out_count / iterations,
        'mean_dd': np.mean(max_drawdowns),
        'mean_return': np.mean(returns),
        'percentiles': {
            5: np.percentile(final_balances, 5),
            10: np.percentile(final_balances, 10),
            25: np.percentile(final_balances, 25),
            50: np.percentile(final_balances, 50),
            75: np.percentile(final_balances, 75),
            90: np.percentile(final_balances, 90),
            95: np.percentile(final_balances, 95)
        }
    }

def generate_visualizations(results, initial_balance, output_dir):
    """Generate Monte Carlo visualization charts."""
    
    final_balances = np.array(results['final_balances'])
    max_drawdowns = np.array(results['max_drawdowns'])
    
    # Figure 1: Distribution of final balances
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    # Plot 1: Final balance distribution
    ax1 = axes[0, 0]
    ax1.hist(final_balances, bins=50, edgecolor='black', alpha=0.7, color='steelblue')
    ax1.axvline(initial_balance, color='red', linestyle='--', linewidth=2, label='Initial Balance')
    ax1.axvline(np.mean(final_balances), color='green', linestyle='-', linewidth=2, label=f'Mean: ${np.mean(final_balances):.0f}')
    ax1.set_xlabel('Final Balance ($)', fontsize=12)
    ax1.set_ylabel('Frequency', fontsize=12)
    ax1.set_title('Distribution of Final Balances (10,000 Iterations)', fontsize=14)
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Plot 2: Cumulative distribution
    ax2 = axes[0, 1]
    sorted_balances = np.sort(final_balances)
    cdf = np.arange(1, len(sorted_balances) + 1) / len(sorted_balances)
    ax2.plot(sorted_balances, cdf, linewidth=2, color='steelblue')
    ax2.axvline(initial_balance, color='red', linestyle='--', linewidth=2, label='Initial')
    ax2.axhline(0.5, color='gray', linestyle=':', alpha=0.5)
    ax2.set_xlabel('Final Balance ($)', fontsize=12)
    ax2.set_ylabel('Cumulative Probability', fontsize=12)
    ax2.set_title('Cumulative Distribution of Final Balances', fontsize=14)
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # Plot 3: Max Drawdown distribution
    ax3 = axes[1, 0]
    ax3.hist(max_drawdowns * 100, bins=50, edgecolor='black', alpha=0.7, color='coral')
    ax3.axvline(np.mean(max_drawdowns) * 100, color='red', linestyle='-', linewidth=2, 
                label=f'Mean: {np.mean(max_drawdowns)*100:.1f}%')
    ax3.set_xlabel('Maximum Drawdown (%)', fontsize=12)
    ax3.set_ylabel('Frequency', fontsize=12)
    ax3.set_title('Distribution of Maximum Drawdowns', fontsize=14)
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # Plot 4: Sample equity curves
    ax4 = axes[1, 1]
    sequences = results['trade_sequences']
    sample_indices = np.random.choice(len(sequences), 50, replace=False)
    for idx in sample_indices:
        ax4.plot(sequences[idx], alpha=0.3, linewidth=0.5)
    
    # Add mean trajectory
    mean_trajectory = np.mean(sequences, axis=0)
    ax4.plot(mean_trajectory, color='red', linewidth=3, label='Mean Trajectory')
    ax4.axhline(initial_balance, color='black', linestyle='--', linewidth=1)
    ax4.set_xlabel('Trade Number', fontsize=12)
    ax4.set_ylabel('Account Balance ($)', fontsize=12)
    ax4.set_title('Sample Equity Curves (50 Random Simulations)', fontsize=14)
    ax4.legend()
    ax4.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'monte_carlo_smc_results.png'), dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"\n  Visualization saved to: {output_dir}/monte_carlo_smc_results.png")

def generate_report(results, stats, signals_df, initial_balance, output_dir):
    """Generate comprehensive Monte Carlo analysis report."""
    
    report = f"""
================================================================================
         MONTE CARLO SIMULATION REPORT - SMC LAYER SIGNALS
================================================================================
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Asset: XAUUSD (Gold)
Strategy: SMC (Smart Money Concepts) Layer Filters

================================================================================
1. SIGNAL DATA OVERVIEW
================================================================================
Total Signals Analyzed: {len(signals_df)}
Date Range: {signals_df['Time'].min().strftime('%Y-%m-%d')} to {signals_df['Time'].max().strftime('%Y-%m-%d')}
Duration: {(signals_df['Time'].max() - signals_df['Time'].min()).days} days

Signal Direction:
  - LONG signals: {len(signals_df[signals_df['Action'] == 'LONG'])} ({len(signals_df[signals_df['Action'] == 'LONG'])/len(signals_df)*100:.1f}%)
  - SHORT signals: {len(signals_df[signals_df['Action'] == 'SHORT'])} ({len(signals_df[signals_df['Action'] == 'SHORT'])/len(signals_df)*100:.1f}%)

================================================================================
2. SIMULATION PARAMETERS
================================================================================
Initial Account Balance: ${initial_balance:.2f}
Risk Per Trade: {RISK_PER_TRADE:.1%}
Reward-to-Risk Ratio: {REWARD_TO_RISK:.1f}:1
Estimated Win Rate: {results['win_rate']:.1%}
Expected Value per Trade: {results['expected_value']:.3f}
Monte Carlo Iterations: {MONTE_CARLO_ITERATIONS:,}

================================================================================
3. MONTE CARLO RESULTS
================================================================================

3.1 Final Balance Statistics
-----------------------------
Mean Final Balance:      ${stats['mean_balance']:,.2f}
Median Final Balance:    ${stats['median_balance']:,.2f}
Standard Deviation:      ${stats['std_balance']:,.2f}
Minimum:                 ${np.min(results['final_balances']):,.2f}
Maximum:                 ${np.max(results['final_balances']):,.2f}

3.2 Percentile Analysis (Risk Assessment)
-----------------------------------------
5th Percentile:         ${stats['percentiles'][5]:,.2f} (Worst 5% of outcomes)
10th Percentile:        ${stats['percentiles'][10]:,.2f} (Bottom 10%)
25th Percentile:        ${stats['percentiles'][25]:,.2f} (Bottom 25%)
50th Percentile:        ${stats['percentiles'][50]:,.2f} (Median outcome)
75th Percentile:        ${stats['percentiles'][75]:,.2f} (Top 25%)
90th Percentile:        ${stats['percentiles'][90]:,.2f} (Top 10%)
95th Percentile:        ${stats['percentiles'][95]:,.2f} (Top 5%)

3.3 Probability Analysis
-----------------------
Probability of Profit:     {stats['prob_profit']*100:.1f}%
Probability of Doubling:   {stats['prob_doubling']*100:.1f}%
Probability of 50% Loss:   {stats['prob_50_loss']*100:.1f}%

3.4 Drawdown Analysis
---------------------
Mean Maximum Drawdown: {stats['mean_dd']*100:.1f}%
Worst Case Drawdown:   {np.max(results['max_drawdowns'])*100:.1f}%

3.5 Return Statistics
---------------------
Mean Return: {stats['mean_return']:+.1f}%
Median Return: {np.median(results['final_balances'])/initial_balance*100 - 100:+.1f}%
Best Case: {np.max(results['final_balances'])/initial_balance*100 - 100:+.1f}%
Worst Case: {np.min(results['final_balances'])/initial_balance*100 - 100:+.1f}%

================================================================================
4. RISK ASSESSMENT & RECOMMENDATIONS
================================================================================

4.1 Risk Rating
---------------
Based on the Monte Carlo simulation:

"""
    
    # Determine risk rating
    if stats['prob_profit'] >= 0.80 and stats['prob_doubling'] >= 0.30:
        risk_rating = "LOW - Strategy shows strong positive expectancy"
    elif stats['prob_profit'] >= 0.60 and stats['prob_doubling'] >= 0.15:
        risk_rating = "MODERATE - Strategy shows positive expectancy with some risk"
    elif stats['prob_profit'] >= 0.50:
        risk_rating = "ELEVATED - Strategy near breakeven, careful monitoring needed"
    else:
        risk_rating = "HIGH - Strategy shows negative expectancy"
    
    report += f"Risk Rating: {risk_rating}\n\n"
    
    report += f"""4.2 Key Insights
----------------
- With a win rate of {results['win_rate']:.1%} and {REWARD_TO_RISK}:1 R/R ratio,
  the strategy has an expected value of {results['expected_value']:.3f} per dollar risked.
  
- {stats['prob_profit']*100:.1f}% of {MONTE_CARLO_ITERATIONS:,} simulations ended in profit.

- The 5th percentile balance of ${stats['percentiles'][5]:,.2f} represents the
  "bad luck" scenario - there's only a 5% chance of doing worse than this.

- Average maximum drawdown of {stats['mean_dd']*100:.1f}% suggests moderate
  volatility in the strategy.

4.3 Recommendations
-------------------
1. Position Sizing: Current risk of {RISK_PER_TRADE:.1%} per trade is appropriate
   given the probability distribution.

2. Expectancy: The strategy's positive expectancy suggests it can be profitable
   over time, but variance is significant ({stats['std_balance']:,.2f} std dev).

3. Risk Management: The {stats['prob_50_loss']*100:.1f}% chance of 50% drawdown
   suggests using proper position sizing and stop losses is critical.

4. Diversification: Consider running this strategy alongside other strategies
   to reduce overall portfolio variance.

================================================================================
5. LAYER FILTER EFFECTIVENESS
================================================================================

The SMC (Smart Money Concepts) layers analyze:
- Killzone Filter: Trading only during London/NY sessions
- Structure: Identifying market structure breaks (BOS/CHOCH)
- Liquidity: Detecting liquidity sweeps
- FVG: Fair Value Gap analysis
- Displacement: Momentum confirmation
- MSS: Market Structure Shift detection

These filters help improve signal quality by:
- Reducing false signals during low-liquidity periods
- Trading with the trend (structure alignment)
- Entering at optimal points (FVG/MSS)

================================================================================
6. CONCLUSION
================================================================================

The Monte Carlo simulation of {MONTE_CARLO_ITERATIONS:,} iterations on {len(signals_df)} 
historical signals indicates:

- Expected final balance: ${stats['mean_balance']:,.2f}
- Expected ROI: {stats['mean_return']:+.1f}%
- Probability of profit: {stats['prob_profit']*100:.1f}%

The strategy demonstrates positive expectancy and can be recommended for live
trading, provided proper risk management is implemented.

================================================================================
                              END OF REPORT
================================================================================
"""
    
    # Save report
    report_path = os.path.join(output_dir, 'monte_carlo_smc_report.md')
    with open(report_path, 'w') as f:
        f.write(report)
    
    print(f"\n  Report saved to: {report_path}")
    
    return report

# ============================================================================
# MAIN EXECUTION
# ============================================================================
def main():
    print("\n" + "="*60)
    print("  MONTE CARLO SIMULATION FOR SMC LAYER SIGNALS")
    print("="*60)
    
    # Step 1: Load signals
    signals_df = load_signals()
    if signals_df is None:
        print("ERROR: Could not load signals. Exiting.")
        return
    
    # Step 2: Analyze session distribution
    signals_df = analyze_session_distribution(signals_df)
    
    # Step 3: Run Monte Carlo simulation
    results = run_monte_carlo_simulation(
        signals_df=signals_df,
        initial_balance=INITIAL_BALANCE,
        risk_per_trade=RISK_PER_TRADE,
        reward_to_risk=REWARD_TO_RISK,
        iterations=MONTE_CARLO_ITERATIONS
    )
    
    # Step 4: Analyze results
    stats = analyze_results(results, INITIAL_BALANCE, MONTE_CARLO_ITERATIONS)
    
    # Step 5: Generate visualizations
    generate_visualizations(results, INITIAL_BALANCE, OUTPUT_DIR)
    
    # Step 6: Generate report
    report = generate_report(results, stats, signals_df, INITIAL_BALANCE, OUTPUT_DIR)
    
    print("\n" + "="*60)
    print("  SIMULATION COMPLETE")
    print("="*60)
    print(f"\nOutput files:")
    print(f"  - {OUTPUT_DIR}/monte_carlo_smc_report.md")
    print(f"  - {OUTPUT_DIR}/monte_carlo_smc_results.png")

if __name__ == "__main__":
    main()
