# Compile the NSIS installer generated by Tauri (PowerShell helper)
# Run this from the repo root or run the script directly in an elevated PowerShell session.

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$nsisDirCandidate = Join-Path $scriptDir '..\src-tauri\target\release\nsis\x64'

try {
    $nsisDir = Resolve-Path -Path $nsisDirCandidate -ErrorAction Stop
} catch {
    Write-Error "NSIS folder not found: $nsisDirCandidate"
    exit 1
}

$nsisDir = $nsisDir.Path
$installerScript = Join-Path $nsisDir 'installer.nsi'
if (-not (Test-Path $installerScript)) {
    Write-Error "Installer script not found: $installerScript"
    exit 1
}

Write-Host "Compiling NSIS installer in $nsisDir..."

# Try common install locations
$possibleMakensis = @(
    "$env:ProgramFiles\NSIS\makensis.exe",
    "$env:ProgramFiles(x86)\NSIS\makensis.exe"
)

$makensis = $null
foreach ($p in $possibleMakensis) {
    if ($p -and (Test-Path $p)) { $makensis = $p; break }
}

if (-not $makensis) {
    $cmd = Get-Command makensis -ErrorAction SilentlyContinue
    if ($cmd) { $makensis = $cmd.Source }
}

if (-not $makensis) {
    Write-Error "makensis.exe not found. Install NSIS and ensure makensis is on PATH: https://nsis.sourceforge.io/Download"
    exit 2
}

Write-Host "Using makensis at: $makensis"

$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $makensis
$psi.Arguments = '"installer.nsi"'
$psi.WorkingDirectory = $nsisDir
$psi.RedirectStandardOutput = $true
$psi.RedirectStandardError = $true
$psi.UseShellExecute = $false
$psi.CreateNoWindow = $true

$proc = New-Object System.Diagnostics.Process
$proc.StartInfo = $psi
$proc.Start() | Out-Null

# Stream output
while (-not $proc.HasExited) {
    $out = $proc.StandardOutput.ReadLine()
    if ($out -ne $null) { Write-Host $out }
}
# flush remaining
while (-not $proc.StandardOutput.EndOfStream) { Write-Host $proc.StandardOutput.ReadLine() }
while (-not $proc.StandardError.EndOfStream) { Write-Error $proc.StandardError.ReadLine() }

$proc.WaitForExit()
$exitCode = $proc.ExitCode
if ($exitCode -eq 0) {
    $outputPath = Join-Path $nsisDir 'nsis-output.exe'
    if (Test-Path $outputPath) {
        Write-Host "Installer built: $outputPath"
    } else {
        Write-Host "makensis completed; check $nsisDir for generated files."
    }
    exit 0
} else {
    Write-Error "makensis exited with code $exitCode"
    exit $exitCode
}
