@echo off
setlocal

rem Compile the NSIS installer generated by Tauri (if present).
rem Run this script from repo root: scripts\compile_nsis_installer.bat

pushd "%~dp0..\src-tauri\target\release\nsis\x64" 2>nul || (
  echo NSIS folder not found: %~dp0..\src-tauri\target\release\nsis\x64
  pause
  exit /b 1
)

echo Compiling NSIS installer in %CD%...

if exist "C:\Program Files\NSIS\makensis.exe" (
  "C:\Program Files\NSIS\makensis.exe" installer.nsi
) else (
  where makensis >nul 2>&1
  if %errorlevel%==0 (
    makensis installer.nsi
  ) else (
    echo NSIS (makensis.exe) not found. Install NSIS from https://nsis.sourceforge.io/Download
    pause
    popd
    exit /b 1
  )
)

echo Installer built at %CD%\nsis-output.exe (default name from script)
pause
popd
endlocal
